
<!--
	Author:		Debabrata Tripathy, IIT Bombay, Mumbai
	Mail ID:	dtriapthy10@gmail.com
	Website:	http://home.iitb.ac.in/~debabratatripathy/
	Phone No:	9004499484
-->	
<?php
  include_once("header.php");
  getHeader(1,"UTSP VLab");
?>

  <div id="photslider">
    <!--  Carousel -->
      <!--  consult Bootstrap docs at 
            http://twitter.github.com/bootstrap/javascript.php#carousel -->
      <div id="myCarousel" class="carousel slide">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
      </ol>
        <div class="carousel-inner">
          <div class="item active">
                <img src="images/workshop1.png" alt="" />
          </div>
          <div class="item">
            <img src="images/workshop1.png" alt="" />
            <!-- <div class="carousel-caption">
              <span>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</span>
              <a class="btn btn-primary" href="#">Register for workshop</a>
            </div> -->
          </div>
        </div><!-- .carousel-inner -->
        <!--  next and previous controls here
              href values must reference the id for this carousel -->
          <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
          <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
      </div><!-- .carousel -->
      <!-- end carousel -->
  </div>
	<div id="body">
  
	<p>Urban Transportation Systems Planning (UTSP) is a core course in the field of Transportation engineering. Modelling of travel demand is the most important aspect of transportation planning. In order to evaluate the present and future performance of a urban transportation networks and to plan for the future infrastructure requirement, a demand model is developed for each urban conglomeration. It starts with defining the study area and dividing them into a number of zones and considering the entire transport network in the system. The database typically includes the current (base year) levels of population, economic activity like employment, shopping space, educational, and leisure facilities of each zone. The classic model is presented as a sequence of four sub models: trip generation, trip distribution, modal split, and trip assignment. It involves descriptive and mathematical analysis of given scenario in different stages and sub stages and thus making it difficult for students to interpret various step and outputs. To simplify these basic concepts graphical user interface becomes a necessity for the user to understand these facts and help them to co-relate the significant mathematical output with the real scenario. In practice the travel demand models are developed with the help of commercials software tools such as TransCAD and Cube Voyager. These tools are very costly and beyond the reach of the teachers and students in the most engineering colleges in India. Only some top institutions in India own these software tools. Even if an institution owns these tools, they are not of much use for teaching an algorithm or a methodology. These tools usually give the final outputs given certain inputs for an experiment, without much interaction with the users. Learning to use these tools is also time consuming thus are not much useful for classroom teaching.</p>

<p>The First step of tradition travel demand model is trip generation, which uses socioeconomic data to estimate both the total number of trips generated and attracted by each zone. The majority of trip-generation studies require multiple regression analysis to develop the prediction equations for the trips generated by various types of land use. Stepwise regression analysis programs allow the analyst to develop and test a large number of potential regression equations using various combinations and transformations of both the dependent and independent variables. Category analysis is a technique for estimating the trip production characteristics of households, which have been sorted into a number of separate categories according to set of properties that characterize the household.</p>
<p>The next step is the allocation of these trips from each zone to various other destination zones in the study area using trip distribution models. The output of the above model is a trip matrix, which denotes the trips from each zone to every other zone.</p>
<p>In the succeeding step the trips are allocated to different modes (car, two-wheeler, transit, walk, etc) based on the modal attributes using the modal split models. It divides the trip matrix for various modes generated to a mode specific vehicle type trip matrix. In Last step, called as traffic assignment, each trip matrix is assigned to the route network of that particular mode using the trip assignment models. There are the different types of traffic assignment models, such as, All-or-nothing, User-equilibrium, System-optimal assignment, and stochastic assignment and dynamic assignment. The primary output of traffic assignment is the link flows from which other outputs such as travel time, emissions, etc. can be derived.</p>
<p>Most current travel forecasting process use some form of the sequential models. The sequential model structure usually composed of four phases namely trip generation, trip distribution, modal split and route assignment. The process of travel-demand forecasting essentially consisting of these four distinct stages is also known as four stage UTP process.To begin exploring Travel Demand Forecasting, click on the respective links given below :</p>

	</div>
<?php
  include_once("footer.php");
  getFooter(1);
?>