<?php
  include_once("header.php");
   getHeader(2,"Trip Generation","");
?> 
<div id ="body">
<h1 class="designation">Trip Generation</h1>
<span class="title">Introduction</span>
 <p class="section">Trip Generation is the first step in the Sequential Demand Modelling arrangement which is also called as the Four Step Transportation Planning Process(FSTP) as mentioned earlier. In order to carry out modelling, the variable consists of total number of person-trips generated by a zone as a dependent variable and the independent variable consists of household and socio- economic factors which influence the trip making behaviour of the person. The data for the independent variable should be attained from an analyst. The output thus obtained consists of trip making or trip ends for each zone within a region.</p>
 <p class="section">In contemporary transportation planning language, A Trip is defined as a one way person movement by a mechanized mode of transport, having two trip ends. The start of the trip is called as origin and the end of trip is called as destination.  Trip is classified as Production or Origin and Attraction or Destination. It should be note that the terminologies used are not identical. To understand with an example consider a single worker on a typical working day making a trip from his house which is in zone <b>P</b>  to his office in Zone <b>Q</b>. Thus his trip origin will be zone <b>P</b> and trip destination will be zone <b>Q</b>. For the return trip from office to house his trip origin will be zone <b>Q</b> and trip Destination will be Zone <b>P</b>.  Thus from the above Example it can be understood that the term Origin and Destination are defined in terms of direction of the trip while Production and Attraction in terms of land use associated with each trip end. Trip Production is the home end of home based trip and is the origin of trip of non home based trip. Trip Attraction is the non home end of home based trip and is the destination of a non home based trip.</p>
<center><img src="images/1.bmp" /></center><br>
<span class="title">Classification of Trips</span>
<p class="section">It has been found that better trip generation models can be obtained if the trips by different purpose are identified and modelled separately.The trips can be classified as given below:</p>
<p class="section"><b>1. Home Based Trip: One of the trip end is home.</b></p>
<p class="section"><b>Example:</b> A trip from home to office.</p>
<p class="section">Following are the list of home based trips that is trip purpose which are classified into five categories:</p>
<p class="section">a. Work Trips</p>
<p class="section">b. School Trips</p>
<p class="section">c. Shopping Trips</p>
<p class="section">d. Social- recreational Trips</p>
<p class="section">e. Other Trips</p>
<p class="section">The first two trips are mandatory trips while other trips are discretional trips. The other trip class encompasses all the trips made for less routine purpose such as health bureaucracy etc.</p>
<br>
<p class="section"><b>2. Non Home based trips: None of the trip end is home.</b></p>
<p class="section"><b>Example:</b> A trip from office to Shopping Mall.</p>
<br>
<p class="section"><b>3. Time based trips</b></p>
<p class="section">The proportion of journey is different by different purposes usually varies with time of the day. Thus the classification is often given as Peak and Off Peak Period Trip.</p>
<p class="section"><b>Example</b></p>
<table class="table table-bordered table-hover">
<tr><th>Time</th><th>Cars</th><th>Bus</th><th>Two Wheelers</th><th>Rickshaw</th></tr>
<tr align="center"><td>7:00 - 7:30</td><td>34</td><td>8</td><td>40</td><td>24</td></tr>
<tr align="center"><td>7:30 - 8:00</td><td>39</td><td>9</td><td>45</td><td>30</td></tr>
<tr align="center"><td>8:00 - 9:30</td><td>45</td><td>12</td><td>55</td><td>35</td></tr>
</table>
<br>
<p class="section"><b>4. Person-type based trips</b></p>
<p class="section">The travel behaviour of an individual is mainly dependent on its Socio-Economic attributes. Following are the categories which are usually employed.</p>
<p class="section">a. Income Level- Poor,  Middle Class, Rich</p>
<p class="section">b. Car Ownership- 0,1,2,3</p>
<p class="section">c. Household Size- 1,2,3,4... etc</p>
<span class="title">Factors influencing Trip Production</span>
<p class="section">a. No. of workers in a household.</p>
<p class="section">b. No. of Students.</p>
<p class="section">c. Household size and composition.</p>
<p class="section">d. The household income.</p>
<p class="section">e. Some proxy of income such as number of cars etc.</p>
<span class="title">Factors influencing Trip Attraction</span>
<p class="section">a. Floor area and number of employment opportunities in retail trade, service, offices manufacturing and wholesale areas.</p>
<p class="section">b. School and college enrolment</p>
<p class="section">c. Other activity centres like transport terminals, sports stadium, major recreational/ cultural/religious places</p>
<p class="section">Table below represents base year data of Trip Production for exact zone.</p>
<table class="table table-bordered table-hover">
<tr><th width="20%">Zone</th><th>Trips Produced</th><th>Home based trips(HBT)</th><th>Non Home based Trips(NHT)</th><th>Car Ownership(CO)</th></tr>
<tr align="center"><td>1</td><td>100</td><td>50</td><td>35</td><td>12</td></tr>
<tr align="center"><td>2</td><td>150</td><td>45</td><td>36</td><td>35</td></tr>
<tr align="center"><td>3</td><td>127</td><td>36</td><td>23</td><td>34</td></tr>
<tr align="center"><td>4</td><td>150</td><td>57</td><td>36</td><td>58</td></tr>
<tr align="center"><td>5</td><td>170</td><td>48</td><td>55</td><td>35</td></tr>
</table>

<p class="section">Similarly Trip Attraction Table is obtained with respect to its influencing variables.</p>
<p class="section">Trip generation study typically involves the application of residential trip production which contains variable that defines the demographic makeup of zonal population and trip attraction that captures the activity of non residential activities within the zone.</p>
<p class="section">In the example given below the zones are connected by a two way link. Each zone will have its own demographic and non residential characteristics depending on which the Trip Generation table is represented below.</p>
<center><img src="images/2.bmp"/></center><br>

<table class="table table-bordered table-hover">
<tr align="center"><td colspan="2" width="30%"><b>Zone</b></td><td><b>Trips Production(P)</b></td><td><b>Trip Attraction(A)</b></td></td>
<tr align="center"><td>1</td><td>2</td><td>20</td><td>34</td></tr>
<tr align="center"><td>2</td><td>2</td><td>25</td><td>25</td></tr>
<tr align="center"><td>2</td><td>1</td><td>35</td><td>55</td></tr>
<tr align="center"><td>2</td><td>3</td><td>67</td><td>70</td></tr>
<tr align="center"><td>3</td><td>2</td><td>55</td><td>75</td></tr>
</table>
<br>
</center>
<p class="section">The procedure to obtain the PA Table (shown above) from the base year condition of Trip Production and Attraction is explained in the next section call Modelling.<br><br>
<span class="title">Modelling Trip Production</b></span>
<p class="section">Modelling basically relates the dependent variable ie trips produced by a zone for aggregated model or household trip production rate for household based models to the corresponding Independent variables characterised by the whole zone or household characteristic respectively. Calibration is done based on the set of observations obtained corresponding to the zones for aggregate model and for disaggregate model  employs a number of base year observations corresponding to an individual household in a sample of household drawn randomly from the region.<br>
Thus we first need to identify what are the relevant variables:<br>
a. Home end <br>
b. Work End<br>
c. Shop End<br></p>
<p class="section">Analytical tools used for Trip Generation Modelling are given below:<br>
<a href="../experiment2/aim.php">1. Regression Model (Regression Analysis) </a><br>
<a href="../experiment3/aim.php">2. Cross Classification Model (Category Analysis)</a><br></p>
<span class="title">Summary</span>
<p class="section">The purpose of trip generation is to estimate the number of trip ends for each zones for the targeted year. The trip end is calculated for different travel purpose within the zone. These trips are represented as residential trip production obtained from household based cross classification tables or non residential trip attractions which is obtained by projection of land use. Trip generation Models that are often used are Multiple Linear Regression Model or Cross Classification Model or involves combination of both.</p>
</div>
 <?php
  include_once("footer.php");
  getFooter(2);
?>   