
<!--
	Author:		Debabrata Tripathy, IIT Bombay, Mumbai
	Mail ID:	dtriapthy10@gmail.com
	Website:	http://home.iitb.ac.in/~debabratatripathy/
	Phone No:	9004499484
-->	
<?php
  include_once("header.php");
  getHeader(5);
?> 
	<div id="body">
    <h1 class="designation">FAQs</h1>
    <ul class="questions">
      <li>What are the assumptions in growth factor methods?<span class="answers">A trip is a one-way person movement by a mechanized mode of transport, having two trip ends, an origin (the start of the trip) and a destination (the end of the trip).
journey is a one-way movement from a point of origin to a point of destination.</span></li>

      <li>What are the limitations of the growth factor methods?<span class="answers">The trip in which at least one of trip ends is home, is called as home based trip.
The trip in which neither of the end is home, is called as non home based trip.</span></li>

      <li>What is trip distribution analysis ?<span class="answers">Trip production - this is defined as the home end of an HB trip or as the origin of NHB trip.
Trip attraction - this is defined as the home end of an HB trip or the destination of NHB trip.
 </span></li>

      <li>What are zones?<span class="answers">If one person goes for the work and then from the work place he goes to workshop then zones behaves as trip production and attraction zone</span></li>
      
      <li>What are Intra-zonal and Inter-zonal trip ?<span class="answers">Trip generation rates are average rates used to estimate how much traffic a specific land use will produce. For example, the amount of traffic generated by a group of homes is different from a business park.</span></li>
      <li>What are other method of trip distribution ?<span class="answers">Regions within the study area that contain homogenous land uses and can be described accurately by only a few variables.</span></li>
    </ul>
  </div>
<?php
  include_once("footer.php");
  getFooter(5);
?>  